AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Check stock for items at a URL.

Globals:
  Function:
    Timeout: 120

Resources:
  StockCheckSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: "Stock Checker Notifications"
      TopicName: "StockCheck"

  StockCheckFn:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      MemorySize: 128
      CodeUri: ./
      Handler: src.stock_check.lambda_function.lambda_handler
      Runtime: python3.12
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt StockCheckSNSTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref StockCheckSNSTopic
      Events:
        Event1:
          Type: ScheduleV2
          Properties:
            Name: StockCheck1
            Description: Event that triggers the lambda every 6 hours
            ScheduleExpression: rate(6 hours)
            State: ENABLED
            Input: |
              {"url": "https://httpbin.org/html",
               "headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/138.0.1"},
               "match": "Availing himself of the mild",
               "match_description": "A known match"}
        Event2:
          Type: ScheduleV2
          Properties:
            Name: StockCheck2
            Description: Event that triggers the lambda every 6 hours
            ScheduleExpression: rate(6 hours)
            State: ENABLED
            Input: |
              {"url": "https://httpbin.org/html",
               "headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/138.0.1"},
               "match": "Are you suggesting coconuts migrate?",
               "match_description": "An excellent movie"}

  StockCheckFnLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: StockCheckFn
    Properties:
      LogGroupName: !Sub /aws/lambda/${StockCheckFn}
      RetentionInDays: 90

  StockCheckFnLogMetricFilter:
    Type: AWS::Logs::MetricFilter
    DependsOn: StockCheckFnLogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${StockCheckFn}
      FilterName: !Sub ${StockCheckFn}-error-filter
      FilterPattern: "?ERROR ?error ?Error ?FAIL ?fail Fail"
      MetricTransformations:
        - MetricName: !Sub ${StockCheckFn}-error
          MetricNamespace: !Sub "/aws/lambda/${StockCheckFn}"
          DefaultValue: 0
          MetricValue: "1"
          Unit: Count

  StockCheckFnCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: StockCheckFnLogMetricFilter
    Properties:
      AlarmName: !Sub ${StockCheckFn}-alarm
      AlarmDescription: "Alarm when 'error' or 'fail' appears in cloudwatch logs."
      Namespace: !Sub "/aws/lambda/${StockCheckFn}"
      MetricName: !Sub ${StockCheckFn}-error
      Statistic: Sum
      Period: 43200 # seconds = 12 hours
      EvaluationPeriods: 1
      Threshold: 2
      TreatMissingData: missing
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref StockCheckSNSTopic
      OKActions:
        - !Ref StockCheckSNSTopic

Outputs:
  StockCheckFn:
    Description: "Function ARN"
    Value: !GetAtt StockCheckFn.Arn
  StockCheckFnIamRole:
    Description: "IAM Role auto created for the Lambda Function"
    Value: !GetAtt StockCheckFnRole.Arn
  StockCheckSNSTopic:
    Description: "SNS Topic ARN"
    Value: !Ref StockCheckSNSTopic
